gsprasannabalaji/bos-buy-commerce

frontend/src/common-components/Button.jsx, frontend/src/pages/Checkout.jsx, frontend/src/pages/Home.jsx, frontend/src/pages/ProductDetail.jsx, frontend/src/pages/ProductListing.jsx
- Added the libraries
- bootstrap, react boostrap, sass
=> Initialized the required libraries and base setup structures

backend/api/app.js, backend/api/controllers/productController, backend/api/models/product.js, backend/api/routes/index.js, backend/api/routes/productroute.js, backend/api/services/productservice.js, backend/package-lock.json, backend/package.json, backend/server.js
=> Backend get product api by productid

frontend/src/common-components/CustomToast.jsx, frontend/src/features/products/productsSlice.js, frontend/src/pages/ProductDetail.jsx, frontend/src/pages/SearchResults.jsx, frontend/src/scss/abstracts/_variables.scss, frontend/src/scss/common-components/CustomToast.scss, frontend/src/scss/style.scss
API Integration
- Product Search API
- Product Detail API
=> integrated the search results and product detail api

backend/.gitignore, backend/api/controllers/productController, backend/api/routes/productroute.js, backend/api/services/productservice.js
Implemented getTopProducts API
=> implemented getTopProducts API

backend/api/controllers/stripe-controller.js, backend/api/routes/index.js, backend/api/routes/stripe-route.js, backend/api/services/stripe-service.js, backend/package-lock.json, backend/package.json, backend/server.js
Integrated the stripe payment gateway using stripe library
=> Added stripe payment api

frontend/src/pages/Cart.jsx
Integrated the stripe payment gateway API
=> Stripe Payment API integration in cart page

frontend/src/common-components/Header.jsx, frontend/src/components/ProductCard.jsx, frontend/src/components/ShoppingCart.jsx, frontend/src/features/cart/cartSlice.js, frontend/src/pages/Cart.jsx, frontend/src/pages/ProductDetail.jsx, frontend/src/pages/SearchResults.jsx
- Updated the shopping cart page UI
- changed the header to sticky
=> Updated the shopping cart page UI and its implementation

backend/api/controllers/product-controller.js, backend/api/models/product.js, backend/api/services/product-service.js, frontend/.env
- Changed a few functionalities for create function for the admin
=> Backend changes for create function for admin

backend/api/controllers/user-controller.js, backend/api/middlewares/authenticateToken.js, backend/api/middlewares/validateEmail.js, backend/api/middlewares/validatePassword.js, backend/api/models/user.js, backend/api/routes/index.js, backend/api/routes/user-route.js, backend/api/services/user-service.js, backend/package-lock.json, backend/package.json
- Implemented the route, services, and middleware for login api.
=> User Login API Implementation

backend/api/controllers/product-controller.js
added search category which got removed in the PR
=> Merge Issue Fix

backend/api/models/product.js, backend/api/services/product-service.js
=> Category bug fix

backend/.env, backend/.gitignore, backend/api/app.js, backend/api/controllers/product-controller.js, backend/api/routes/product-route.js, backend/api/services/product-service.js
=> Delete and Edit API Added

frontend/src/App.jsx, frontend/src/app/store.js, frontend/src/common-components/Header.jsx, frontend/src/custom-hooks/useCookieVerifier.jsx, frontend/src/features/user/userSlice.js, frontend/src/pages/Login.jsx, frontend/src/scss/abstracts/_variables.scss, frontend/src/scss/layout/_header.scss, frontend/src/scss/pages/Login.scss, frontend/src/scss/style.scss
- Implemented the login page
- Updated the changes for login and logout
=> Login Implementation for frontend

backend/api/app.js, backend/api/routes/user-route.js, backend/api/services/user-service.js, backend/package-lock.json, backend/package.json
- Installed required libraries
- Added the Implementation for cookie , clear cookies
=> Added the Implementation for cookie , clear cookies 

backend/api/routes/stripe-route.js, backend/api/services/stripe-service.js
- Stripe payment integration updates
=> Updated the stripe payment integration

backend/api/controllers/stripe-controller.js, backend/api/models/orders.js, backend/api/routes/stripe-route.js, backend/api/services/stripe-service.js
- Order Creation Implementation
=> added the feature for stripe order creation

backend/api/controllers/user-controller.js, backend/api/routes/user-route.js, backend/api/services/user-service.js
=> signup api

frontend/src/common-components/Layout.jsx
- Added the protected route for products, searchResults route
=> Protected route for products, searchResults route

frontend/src/features/products/productsSlice.js, frontend/src/pages/ProductDetail.jsx, frontend/src/scss/pages/ProductDetail.scss, frontend/src/scss/style.scss
- Added the Image Preview Section
=> Image Preview Section

frontend/src/common-components/Header.jsx, frontend/src/components/ShoppingCart.jsx, frontend/src/components/TopProducts.jsx, frontend/src/scss/abstracts/_placeholders.scss, frontend/src/scss/abstracts/_variables.scss, frontend/src/scss/components/_buttons.scss, frontend/src/scss/layout/_header.scss, frontend/src/scss/style.scss
- Initialized the variables
- Navbar UI updates
- Link & Button UI changes
- Added placeholders and reusable styles
=> UI Updates (Navbar, Button & Links)

frontend/src/common-components/Footer.jsx, frontend/src/components/ProductCategory.jsx, frontend/src/scss/components/ProductCategory.scss, frontend/src/scss/components/_buttons.scss, frontend/src/scss/layout/_footer.scss, frontend/src/scss/style.scss
- Footer Link
- Primary Button updates for product category
- Product Details Cart Addition Fix
=> UI Updates & bug fix

backend/api/services/product-service.js, backend/api/services/stripe-service.js
=> Backend - env variable addition fix

frontend/src/pages/ProductDetail.jsx
- added the product details cart fix
=> added the product details cart fix

frontend/src/common-components/Header.jsx, frontend/src/components/ProductCard.jsx, frontend/src/components/ProductItem.jsx, frontend/src/scss/abstracts/_placeholders.scss, frontend/src/scss/layout/_header.scss
- Link Updates
- Hover styling
=> UI Updates

frontend/src/App.jsx, frontend/src/common-components/ScrollToTop.jsx, frontend/src/common-components/WithLayout.jsx, frontend/src/pages/ProductDetail.jsx, frontend/src/pages/SearchResults.jsx
- Scroll Top Updates 
- Toast updates
=> Scroll Top Updates & Toast updates

backend/api/controllers/stripe-controller.js, backend/api/models/orders.js, backend/api/routes/stripe-route.js, backend/api/services/stripe-service.js
- Updated the logic for payment checkout
=> Updated the logic for payment checkout

frontend/src/App.jsx, frontend/src/common-components/AdminHeader.jsx, frontend/src/common-components/Header.jsx, frontend/src/common-components/Layout.jsx, frontend/src/common-components/ScrollToTop.jsx, frontend/src/components/OrderItem.jsx, frontend/src/components/ProductCategory.jsx, frontend/src/components/ProductItem.jsx, frontend/src/components/TopProducts.jsx, frontend/src/custom-hooks/useCookieVerifier.jsx, frontend/src/features/cart/cartSlice.js, frontend/src/features/loader/loaderSlice.js, frontend/src/features/orders/ordersSlice.jsx, frontend/src/features/products/productsSlice.js, frontend/src/features/toast/toastSlice.js, frontend/src/features/user/userSlice.js, frontend/src/pages/AddProducts.jsx, frontend/src/pages/AdminHome.jsx, frontend/src/pages/AllOrders.jsx, frontend/src/pages/Cart.jsx, frontend/src/pages/Login.jsx, frontend/src/pages/Orders.jsx, frontend/src/pages/ProductDetail.jsx, frontend/src/pages/SearchResults.jsx, frontend/src/pages/Signup.jsx
=> frontend file comments added

README.md
updated the readme for the project
=> updated the readme for the project

backend/api/app.js, backend/api/controllers/order-controller.js, backend/api/controllers/product-controller.js, backend/api/routes/index.js, backend/api/routes/order-route.js, backend/api/routes/product-route.js, backend/api/routes/stripe-route.js, backend/api/routes/user-route.js, backend/api/services/order-service.js, backend/api/services/product-service.js, backend/api/services/stripe-service.js
=> backend comments added
